FROM ubuntu:16.04
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
RUN pip install --upgrade pip
#RUN python3.7 -m pip install --upgrade pip
COPY . /app 
WORKDIR /app
RUN pip install -r requirements.txt #
ENTRYPOINT ["python"] 
CMD  ["app.py"]
